package exception;

public class ValidationUtil {
	public static void main(String[] args) throws TestException {
		
		Account account = new Account("Agim", "2");
	
		try {
			
		} except (Throwable e) {
			e.printStackTrace();
		}
	}
}
